services:
  api-contas:
    image: registry.tasso.dev.br/gerenciador-financeiro-backend:20260217.1
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${POSTGRES_DB:-gestorfinanceiro};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres}
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__Issuer=GestorFinanceiro
      - JwtSettings__Audience=GestorFinanceiro
      - JwtSettings__AccessTokenExpirationMinutes=1440
      - JwtSettings__RefreshTokenExpirationDays=7
      - AdminSeed__Name=${ADMIN_NAME:-Administrador}
      - AdminSeed__Email=${ADMIN_EMAIL:-admin@gestorfinanceiro.local}
      - AdminSeed__Password=${ADMIN_PASSWORD:-mudar123}
      - Cors__AllowedOrigins__0=https://contas.tasso.dev.br
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.api-contas.entrypoints=websecure
        - traefik.http.routers.api-contas.rule=Host(`api-contas.tasso.dev.br`)
        - traefik.http.routers.api-contas.tls=true
        - traefik.http.routers.api-contas.tls.certresolver=cloudflare-resolver
        - traefik.http.services.api-contas.loadbalancer.server.port=8080
        - traefik.docker.network=traefik-public
    networks:
      - traefik-public
    volumes:
      - api_dataprotection_keys:/root/.aspnet/DataProtection-Keys
    extra_hosts:
      - mssql.tasso.dev.br:192.168.0.100

  frontend-contas:
    image: registry.tasso.dev.br/gerenciador-financeiro-frontend:20260217.1
    environment:
      - API_URL=https://api-contas.tasso.dev.br/api/v1
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend-contas.entrypoints=websecure
        - traefik.http.routers.frontend-contas.rule=Host(`contas.tasso.dev.br`)
        - traefik.http.routers.frontend-contas.tls=true
        - traefik.http.routers.frontend-contas.tls.certresolver=cloudflare-resolver
        - traefik.http.services.frontend-contas.loadbalancer.server.port=80
        - traefik.docker.network=traefik-public
    networks:
      - traefik-public
    extra_hosts:
      - api-contas.tasso.dev.br:192.168.0.100

networks:
  traefik-public:
    external: true

volumes:
  api_dataprotection_keys:
